name: Export release
run-name: "Creating release for commit: ${{ github.event.head_commit.message }}"
on: 
  push:
    branches:
    - main
jobs:
  create-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-release]')"
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.5.0 # Specify the Godot version
          use-dotnet: false # If your project uses C#
          include-templates: true # Adds export templates
      - name: Run Godot command
        run: |
          cd roanoke
          godot --headless --export-debug "Web" ../docs/index.html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './docs' # Replace with the path to your built site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: create-release # Ensures the build job completes first
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
